[package]
name = "declaration-engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4"
linked-hash-map = "0.5.6"
colored = "2.0.0"
